export const Style: Record<number, string> = {
  0: 'Normal',
  1: 'Sideways',
  2: 'W-Only',
  3: 'Scroll',
  4: '400 Velocity',
  5: 'Half-Sideways',
  6: 'A/D-Only',
  7: 'Segmented',
  8: 'Low Gravity',
  9: 'Slow Motion',
  10: 'TAS',
  11: 'Stamina',
  12: 'ezscroll',
  13: 'fairscroll',
  14: 'backwards',
  15: 'doublejump',
  16: 'Autosync',
  17: 'KZ',
  18: '_strafe',
  19: 'Optimizer',
  20: 'tagteam',
  21: 'Unreal',
  22: 'Speedrun',
  23: 'Speedrun Slowmo',
};
