name: Nest.js Backend CI/CD

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Build application
        run: yarn build

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        env:
          NODE_ENV: production
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            cd ~/services/surfing4fun-back
            git fetch origin master
            git reset --hard origin/master
            yarn install --frozen-lockfile
            yarn db:generate
            yarn build
            pm2 reload dashboard-api --update-env || pm2 start dist/master.js --name dashboard-api
          EOF
