# .github/workflows/ci-cd.yml
name: CI/CD

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy to EC2 via SSH
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            cd ~/services/surfing4fun-back
            git fetch origin master
            git reset --hard origin/master
            yarn install --frozen-lockfile
            yarn db:generate
            yarn build
            pm2 restart dashboard-api --update-env
